CREATE TABLE housing_data (
    region_id INT,
    region_name TEXT,
    region_type TEXT,
    state_name TEXT,
    size_rank INT,
    date DATE,
    zhvi_all_homes NUMERIC,
    zhvi_single_family NUMERIC,
    zhvi_condo NUMERIC,
    sales_count_sfr NUMERIC,
    inventory_sfr NUMERIC,
    year INT,
    month INT,
    unemployment_rate NUMERIC,
    median_income NUMERIC,
    population NUMERIC,
    num_major_disasters_last_12mo INT,
    major_disaster_declared BOOLEAN,
    most_recent_disaster_type TEXT,
    state_full TEXT,
    sales_tax NUMERIC,
    income_tax NUMERIC
);
